version: '3.7'

services:
        web:
                build: 
                        context: ./chp_api
                        dockerfile: Dockerfile.prod
                command: gunicorn -c gunicorn.config-prod.py --env DJANGO_SETTINGS_MODULE=chp_api.settings.production chp_api.wsgi:application --bind 0.0.0.0:8000
                volumes:
                        - static_volume:/home/chp_api/web/staticfiles
                expose:
                        - 8000
                env_file:
                        - ./.env.prod
                depends_on:
                        - db
        db:
                image: postgres:12.0-alpine
                volumes:
                        - postgres_data:/var/lib/postgresql/data/
                environment:
                        - POSTGRES_USER=chp_api_user
                        - POSTGRES_PASSWORD=chp_api_user
                        - POSTGRES_DB=chp_api_prod
                env_file:
                        - ./.env.prod.db
        nginx:
                build: ./nginx
                volumes:
                        - static_volume:/home/chp_api/web/staticfiles
                ports:
                        - 80:80
                depends_on:
                        - web

volumes:
        postgres_data:
        static_volume:
