apiVersion: v1
kind: Service
metadata:
  name: {{ include "chp.fullname" . }}
  labels:
    {{- include "chp.labels" . | nindent 4}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx