apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chp.fullname" . }}-startup
  labels:
    app.kubernetes.io/name: {{ include "chp.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  startup.sh: |-
#!/bin/bash
python3 manage.py makemigrations
python3 manage.py migrate --noinput
python3 manage.py collectstatic --no-input